//------------------------------------------------------------------------
// Copyright(c) 2024 oxa.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"Knob.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"Knob VST3 (64Bit)"
#else
#define stringFileDescription	"Knob VST3"
#endif
#define stringCompanyName		"oxa\0"
#define stringLegalCopyright	"Copyright(c) 2024 oxa."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
